---
title: "Seurat_tail_annotations"
output: html_document
date: "2025-07-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
library(ggplot2)
library(dplyr)
library(Seurat)
library(scCustomize)

# Make it so my computer can actually run this code
#options(future.globals.maxSize = 1024^4)
```

# Load tail file
```{r}
tail <- LoadSeuratRds(file = "tail_final.rds")

# to save
#saveRDS(tail, file = "tail_final.rds")
```

# Run through basic identifiers to facilitate exploring
```{r}
tail[[]]
FeaturePlot(tail, reduction = "umap.rpca", features = "nCount_RNA")
FeaturePlot(tail, reduction = "umap.rpca",  features = "nFeature_RNA")
DimPlot(tail, reduction = "umap.rpca",  group.by = "cell_types", label = TRUE)
DimPlot(tail, reduction = "umap.rpca",  group.by = "seurat_clusters", label = TRUE)
DimPlot(tail, reduction = "umap.rpca",  group.by = "seurat_cell_types", split.by = "Sample", label = FALSE)
DimPlot(tail, reduction = "umap.rpca",  split.by = "Sample", label = TRUE)
DimPlot(tail, reduction = "umap.rpca",  group.by = "Phase")
DimPlot(tail, reduction = "umap.rpca",  group.by = "doublet_finder")
```

# Identify neural clusters based off of expression
```{r}
# Neural Progenitor Cells 34 4 30 46 3 
# Differentiating Neurons 18
# Neurons 41 32 6 15 40 39
FeaturePlot(tail,  reduction = "umap.rpca", features = c("sox2", "tubb2b", "pax6"))

```

# Non neural cells, excluding muscle
```{r}
# Immune Cells 12 24 43
FeaturePlot(tail,  reduction = "umap.rpca", features = c("arhgdib", "lcp1", "rac2", "mpo", "slurp1"))

# Epithelial Cells 45
FeaturePlot(tail,  reduction = "umap.rpca", features = c("ptprb", "pmp2", "stab2", "pecam1", "CD93"))

# Erythrocytes 44
FeaturePlot(tail,  reduction = "umap.rpca", features = c("hba4", "hbd", "nt5dc4", "epor", "slc39a8"))

# Notochord, some subgrouping but generally 10 17 38
FeaturePlot(tail,  reduction = "umap.rpca", features = c("epyc", "not", "shh", "foxp1"))

# Secretory Cells 20
FeaturePlot(tail,  reduction = "umap.rpca", features = c("grb14", "chst9l.2", "spdef"))

# Melanocytes 38
FeaturePlot(tail,  reduction = "umap.rpca", features = c("pmel", "mlana", "slc45a2", "tyr", "mitf", "dct"))

# Schwann Cells 14 42
FeaturePlot(tail,  reduction = "umap.rpca", features = c("gldn", "sox10", "pax3", "slc45a2", "slc35f1", "chd19", "kcn15", "gpm6b"))

# Ionocytes 47
FeaturePlot(tail,  reduction = "umap.rpca", features = c("atp6v1b1", "foxi1", "slc26a4.3", "mab21l3", "ca12", "atp6v0a4", "slc16a3"))

# Basal Cells 36 23 29
FeaturePlot(tail,  reduction = "umap.rpca", features = c("tp63", "pfn1", "sp9"))

# Goblet Cells 27 13 25
FeaturePlot(tail, reduction = "umap.rpca",  features = c("cldn4", "gjb1", "egfl6"))
```

# Muscle cells
```{r}
# Skeletal Muscle 11 1 21 37 9 33 22 26 19
FeaturePlot(tail, reduction = "umap.rpca",  features = c("myh6", "actc1", "tpm1", "ryr1", "xirp1", "myoz2", "cripto.3", "ckm", "myf6", "myl1", "ckm", "dupd1"))

# Satellite Cells 7 5 31
FeaturePlot(tail, reduction = "umap.rpca",  features = c("PAX7", "lurap1l", "myf5", "megf10", "npb", "efemp2", "itga6", "myog"))

# PSM 28 and some of 30 -> subcluster?
FeaturePlot(tail, reduction = "umap.rpca",  features = c("tnn", "kank1", "tbx6", "hes7.2", "dlc", "pcdh8i", "tbxt"))

# Vascular Smooth Muscle # integrated into muscle cluster
FeaturePlot(tail,  reduction = "umap.rpca", features = c("rassf9", "agtr1", "myh11"))

```

# Mesodermal clusters
```{r}
# Syndetome 0, 2, 8
FeaturePlot(tail, reduction = "umap.rpca",  features = c("SCX", "meox2", "PAX7", "lix1", "foxc1", "pax1", "zic1"))

# Somitic Mesenchyme 35
FeaturePlot(tail, reduction = "umap.rpca",  features = c("pax9", "zic1", "wnt11", "prrx1", "bmp4", "ndnf"))

# Dermatome- hard to tell apart from satellite cells -> I just labeled everything the satellite cells
FeaturePlot(tail, reduction = "umap.rpca",  features = c("myod1", "myf6", "myog", "pax3", "myf5", "fgfr4", "PAX7", "apln", "snai1", "ihh", "uncx", "tbxt"))

# Sclerotome 16
FeaturePlot(tail, reduction = "umap.rpca",  features = c("pax1", "pax9", "sox9", "nkx3-2", "foxc2", "zic1", "twist1", "crispld1", "tspan4", "gas2"))

# Myotome
FeaturePlot(tail, reduction = "umap.rpca",  features = c("pax1", "pax9", "sox9", "foxc1", "foxc2", "zic1"))
```

# Look for more cell type markers
```{r}
tail.markers <- FindAllMarkers(tail, only.pos = TRUE, group.by = "seurat_clusters")
tail.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 20) %>%
    ungroup() -> top10
FeaturePlot(tail, features = (top10[which(top10$cluster == "50"),] )$gene)

# Mystery flagella cilia populations "dnah3+ Cells" 49
FeaturePlot(tail, reduction = "umap.rpca",  features = c("foxj1", "mcc", "foxj1.2", "mcidas", "notch1", "cfap43", "bicc1", "pax8", "dnah3"))

# Mystery other population 50 "cnfn+ Epidermal Cells" 
FeaturePlot(tail, reduction = "umap.rpca",  features = c("ehf", "avd", "ptk6", "cnfn.1"))
```

# Add names of cell clusters
```{r}
tail@meta.data$seurat_cell_types <- as.character(tail@meta.data$seurat_clusters)

tail@meta.data$seurat_cell_types =
  dplyr::recode(tail@meta.data$seurat_cell_types,
                "0" = "Syndetome",
                "1" = "Skeletal Muscle",
                "2" = "Syndetome",
                "3" = "Neural Progenitor Cells",
                "4" = "Neural Progenitor Cells",
                "5" = "Satellite Cells",
                "6" = "Neurons",
                "7" = "Satellite Cells", 
                "8" = "Syndetome",
                "9" = "Skeletal Muscle",
                "10" = "Notochord",
                "11" = "Skeletal Muscle",
                "12" = "Immune Cells",
                "13" = "Goblet Cells",
                "14" = "Schwann Cells",
                "15" = "Neurons",
                "16" = "Sclerotome",
                "17" = "Notochord",
                "18" = "Differentiating Neurons",
                "19" = "Skeletal Muscle",
                "20" = "Secretory Cells",
                "21" = "Skeletal Muscle",
                "22" = "Skeletal Muscle",
                "23" = "Basal Cells",
                "24" = "Immune Cells",
                "25" = "Goblet Cells",
                "26" = "Skeletal Muscle",
                "27" = "Goblet Cells",
                "28" = "Presomitic Mesoderm",
                "29" = "Basal Cells",
                "30" = "Neural Progenitor Cells",
                "31" = "Satellite Cells",
                "32" = "Neurons",
                "33" = "Skeletal Muscle",
                "34" = "Neural Progenitor Cells",
                "35" = "Somitic Mesenchyme",
                "36" = "Basal Cells",
                "37" = "Skeletal Muscle",
                "38" = "Notochord",
                "39" = "Neurons",
                "40" = "Neurons",
                "41" = "Neurons",
                "42" = "Schwann Cells",
                "43" = "Immune Cells",
                "44" = "Erythrocytes",
                "45" = "Epithelial Cells",
                "46" = "Neural Progenitor Cells",
                "47" = "Ionocytes",
                "48" = "Melanocytes",
                "49" = "dnah3+ Cells",
                "50" = "cnfn+ Epidermal Cells")

# Double check identification
DimPlot(tail, reduction = "umap.rpca",  group.by = "seurat_cell_types", label = FALSE)
DimPlot(tail, reduction = "umap.rpca",  group.by = "seurat_clusters", label = TRUE)
```

# Visualize cell types over sample
```{r}
DimPlot(tail, reduction = "umap.rpca",  group.by = "seurat_cell_types", split.by = "Sample", label = FALSE)
```

# Save tail file
```{r}
saveRDS(tail, file = "tail_final.rds")
```
